In [1]:
import pandas as pd
import numpy as np
import pickle
import seaborn as sns; sns.set()
import matplotlib.pyplot as plt
import pandas_profiling
import os
from datetime import datetime, timedelta
import dateutil.relativedelta
import gc

pd.set_option('display.max_columns',None)

In [2]:
# Changing path
os.chdir('/../../../mnt') 
# Transacction Path
input_PATH = 's3-refined-popular/data_orig/transacciones/pasivo/'

In [7]:
file_name = os.path.join(input_PATH,'transacciones_pasivo_aaatr_M202002.csv')
data_tx_tdc = pd.read_csv(file_name,sep=';',encoding='latin-1')
print(data_tx_tdc.shape)
data_tx_tdc.head()

/home/jupyter/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3049: DtypeWarning: Columns (4) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

(18767035, 53)

,SK_CLIENTE,ID_CLIENTE,AAATR_ACO_REFERE,AAATR_ACO_TERCER,AAATR_ACO_USUAR,AAATR_DCO_ISPEC,AAATR1_ACO_BANCO,AAATR1_ACO_CAUSA,AAATR1_ACO_CONCE,AAATR1_ACO_JORNA,AAATR1_ACOESTCUE,AAATR1_ACOTIPCUE,AAATR_ACU_OFICI,AAATR_ACU_PRODU,AAATR_ACUDIGVER,AAATR_ACUNUMCUE,AAATR1_ACUOFIDES,AAATR_AFEAPLREL,AAATR1_DCO_OFICI,AAATR1_DCO_TERMI,AAATR1_DCO_TRANS,AAATR1_DCODEBCRE,AAATR1_TCN_DOCUM,AAATR1_TCOMODOPE,AAATR1_TDIAPLANT,AAATR_TFE_OFICI,AAATR_TFE_TRANS,AAATR_TFEINGTRA,AAATR_THO_TRANS,AAATR1_TNU_REVER,AAATR1_TNU_TRANS,AAATR_TNUDOCTRA,AAATR1_TSE_AUTOR,AAATR1_TSE_EXCEP,AAATR1_TSE_REVER,AAATR1_TSE_SUPER,AAATR1_TSEDIAANT,AAATR1_TSELIMEXC,AAATR_TVA_CANUTI,AAATR_TVA_CHEQUE,AAATR_TVA_MOVIM,AAATR_TVA_OTRO1,AAATR_TVA_OTRO2,AAATR_TVACHELOC,AAATR1_ACOTIPVAL,AAATR1_ACOTRAOFI,AAATR1_ANUSECOFI,AAATR1_ASEMOVAUT,AAATR_TFE_EXTRA,AAATR_TFE_REAL,PERIODO,YEAR1,MES1
0,2714934,845452294037556202,0550482800009276,000800186061,1010213684,AC202,51,700,1,1,1,2,9,110,8,6,9,20200212,933,934211,4,2,0,1,0,20200212,20200212,20200212,15584773,0,569509,513569509,2,0,2,2,2,0,"0000000000000,00","0000000000000,00","0000000159493,76","0000000000000,00","0000000000000,00","0000000000000,00",0,0,9509,1,20200212,20200212,202002,2020,2
1,2714934,845452294037556202,,,79857343,AC202,0,9,1,1,1,2,9,110,6,7,9,20200228,9,9102,4,2,0,1,0,20200228,20200228,20200228,9354418,0,120,5756277,0,0,2,1,2,0,"0000000000000,00","0000000000000,00","0000025130032,00","0000000000000,00","0000000000000,00","0000000000000,00",0,0,120,2,20200228,20200228,202002,2020,2
2,2714934,845452294037556202,,000800186061,89008621,AC202,683,700,1,1,1,2,9,110,6,7,9,20200219,933,934211,4,2,0,1,0,20200219,20200219,20200219,11245585,0,687944,833687944,2,0,2,2,2,0,"0000000000000,00","0000000000000,00","0000004084738,00","0000000000000,00","0000000000000,00","0000000000000,00",0,0,7944,1,20200219,20200219,202002,2020,2
3,2714934,845452294037556202,,,28968546,AC200,0,0,1,1,1,2,9,110,6,7,9,20200217,362,362104,5,2,0,1,0,20200217,20200217,20200217,9102489,0,693,36202,0,0,2,2,2,0,"0000000000000,00","0000000000000,00","0000001236000,00","0000000000000,00","0000000000000,00","0000000000000,00",0,0,693,2,20200217,20200217,202002,2020,2
4,2714934,845452294037556202,,000800146323,1010213684,AC402,0,700,1,1,1,2,9,110,6,7,9,20200220,933,934200,35,1,0,2,0,20200220,20200220,20200220,13242373,0,177,2821873,0,0,2,2,2,0,"0000000000000,00","0000000000000,00","0000004084738,00","0000000000000,00","0000000000000,00","0000000000000,00",0,0,177,1,20200220,20200220,202002,2020,2

In [ ]:
data_tx_tdc.AAATR_ACO_REFERE.value_counts()

In [ ]:
data_tx_tdc[data_tx_tdc["AAATR_ACO_REFERE"]]

In [ ]:
data_tx_tdc.head(2).AAATR_ACO_REFERE.value_counts()

In [ ]:
data_tx_tdc.AAATR_ACO_REFERE.isnull()

In [ ]:
data_tx_tdc['AAATR_ACO_REFERE'].isnull().sum()/len(data_tx_tdc)

In [ ]:
data_tx_tdc["AAATR_ACO_REFERE"].astype(float)

In [ ]:
data_tx_tdc["AAATR_ACO_REFERE"].unique()

In [ ]:
data_tx_tdc["AAATR_ACO_REFERE"]=data_tx_tdc["AAATR_ACO_REFERE"].str.strip()

In [ ]:
data_tx_tdc["AAATR_ACO_REFERE"].unique()

In [ ]:
data_tx_tdc["AAATR_ACO_REFERE"]==''