In [1]:
import numpy as np
import pandas as pd
pd.set_option('max_columns',None)
pd.set_option('max_rows',None)

In [2]:
import s3fs
import pyarrow as pa
import pyarrow.parquet as pq

def spark_read_parquet(s3_url: str, **args):
    fs = s3fs.S3FileSystem()
    # Leyendo base
    dataset = pq.ParquetDataset(s3_url, filesystem=fs)
    table = dataset.read()
    dataframe = table.to_pandas()

    del dataset, table

    return dataframe

fs = s3fs.S3FileSystem()

## Filtrando libranzas

In [3]:
## Leyendo base libranzas ciclo de vida

mes = '11'
anio = '2021'

str_date = pd.to_datetime(anio+'-'+mes, format = '%Y-%m')
mes = str((str_date - np.timedelta64(20, 'D')).month) if (str_date - np.timedelta64(20, 'D')).month > 9 else '0' + str((str_date - np.timedelta64(20, 'D')).month)
anio = str(int(anio)-1) if mes == '01' else anio

path = 's3://data-bpop-dev-sandbox/estandarizado/productos/libranzas/productos_libranzas_dwh_M'+anio+mes
path

's3://data-bpop-dev-sandbox/estandarizado/productos/libranzas/productos_libranzas_dwh_M202110'

In [4]:
# Leyendo base
dataset = pq.ParquetDataset(path, filesystem=fs)
table = dataset.read()
lib = table.to_pandas()
lib = lib.drop_duplicates()

del dataset, table

In [5]:
print(lib.shape)
lib.head()

(3235686, 68)

,sk_cliente,id_cliente,sk_rc_libranza,id_rc_libranza,sk_fe_radicacion,sk_fe_aprobacion,sk_fe_desembolso,sk_fe_finalizacion,sk_fe_estado_actual,sk_convenio_libranza,sk_persona,dk_persona,sk_oficina,sk_producto_servicio,sk_clasificacion_tradicional,cd_oficina,cd_originador,ds_originador,cd_segmento_lib,ds_segmento_lib,cd_subsegmento_lib,ds_subsegmento_lib,no_solicitud,fe_solicitud,vl_monto_solicitado,mp_reestructurado,no_obligacion,fe_desembolso,vl_monto_aprobado,vl_recapitalizacion,vl_monto_desembolsado,no_cuotas,fe_finalizacion,no_meses_per_gracia,vl_total_cuota,fe_exigibilidad_cuota_1,cd_estado_actual,ds_estado_actual,fe_estado_actual,vl_tasa,vl_tasa_efectiva_anual,cd_modalidad_pag_int,ds_modalidad_pag_int,cd_periodicidad_pag_int,ds_periodicidad_pag_int,cd_base_liquidacion,cd_tipo_libranza,ds_tipo_libranza,cd_tipo_credito,ds_tipo_credito,cd_tipo_colocacion,ds_tipo_colocacion,no_obligacion_novada,vl_monto_novado,mp_compra_ind_cartera,mp_afecta_desp_nomina,cd_linea_credito,fe_carga,fe_actua,no_particion,cd_sector,cd_subsector,cd_tipo_pagaduria,ds_sector,ds_subsector,ds_tipo_pagaduria,standard_id,id_cli
0,61862,102652295880533801,2712776,1000003*13544804*LB*48003090041927,None,None,2017-07-07,2025-11-05,2021-10-05,14689,743653,1000003*13544804,46,27,None,480,1,Banco Popular,5,Policia,5,Policia,48003090052674,2017-07-07,38800000.0,0,48003090041927,2017-07-07,38800000.0,0.0,21424925,99,2025-11-05,0,711983,2017-08-05,70,CREDITO ACTIVO,2021-10-05,15.48,16.6269,V,Vencido,M,Mensual,360,1,Organica,0000000000000000000000000000000000000000000000...,Novacion,9,9-PEN 1 SM 75-79 AÃO 364 DIA,0,16811819.0,0,0,66,2019-04-12,2021-10-07,1,1,21,1,ORDEN NACIONAL,"OTROS POLICÍA, FONDO ROTATORIO ARMADA Y EJERCITO",NACIONAL CENTRALIZADA,1000003,13544804
1,61862,102652295880533801,2637253,1000003*13544804*LB*49403010023262,None,None,2012-10-25,2019-12-05,2017-07-07,16572,743653,1000003*13544804,50,27,None,494,1,Banco Popular,5,Policia,5,Policia,49403010027507,2012-10-22,36100000.0,0,49403010023262,2012-10-25,36100000.0,0.0,27615927,84,2019-12-05,0,648905,2012-12-05,99,CANCELADO,2017-07-07,12.60,13.3537,V,Vencido,M,Mensual,360,1,Organica,0000000000000000000000000000000000000000000000...,Novacion,1,1-ORD HST 50 AÃO 364 DIA,0,5678287.0,0,0,66,2019-04-12,2021-08-25,0,1,21,1,ORDEN NACIONAL,"OTROS POLICÍA, FONDO ROTATORIO ARMADA Y EJERCITO",NACIONAL CENTRALIZADA,1000003,13544804
2,61862,102652295880533801,1993043,1000003*13544804*LB*48003010300770,None,None,2011-02-15,2014-04-05,2012-10-25,22822,743653,1000003*13544804,46,27,None,480,1,Banco Popular,5,Policia,5,Policia,48003010331586,2011-02-14,10100000.0,0,48003010300770,2011-02-15,10100000.0,0.0,8806227,36,2014-04-05,0,352499,2011-04-05,99,CANCELADO,2012-10-25,15.48,16.6269,V,Vencido,M,Mensual,360,1,Organica,0000000000000000000000000000000000000000000000...,Novacion,1,1-ORD HST 50 AÃO 364 DIA,0,791357.0,0,0,66,2019-04-12,2021-08-25,0,1,6,1,ORDEN NACIONAL,Policia Nacional,NACIONAL CENTRALIZADA,1000003,13544804
3,61862,102652295880533801,1931922,1000003*13544804*LB*48003010265425,None,None,2009-12-07,2011-07-05,2011-02-15,22822,743653,1000003*13544804,46,27,None,480,1,Banco Popular,5,Policia,5,Policia,48003010290326,2009-12-04,2150000.0,0,48003010265425,2009-12-07,2150000.0,0.0,2043187,18,2011-07-05,0,135833,2010-01-05,99,CANCELADO,2011-02-15,16.68,18.0162,V,Vencido,M,Mensual,360,1,Organica,0000000000000000000000000000000000000000000000...,Nueva,1,1-ORD HST 50 AÃO 364 DIA,0,0.0,0,0,66,2019-04-12,2021-08-25,0,1,6,1,ORDEN NACIONAL,Policia Nacional,NACIONAL CENTRALIZADA,1000003,13544804
4,61862,102652295880533801,160085,1000003*13544804*LB*22003010064842,None,None,2003-05-27,2005-07-05,2005-07-21,12311,743653,1000003*13544804,219,27,None,220,1,Banco Popular,5,Policia,5,Policia,22003010068205,2003-05-21,2000000.0,0,22003010064842,2003-05-27,2000000.0,0.0,1882077,24,2005-07-05,0,107850,2003-07-05,99,CANCELADO,2005-07-21,26.10,25.7097,V,Vencido,M,Mensual,360,1,Organica,0000000000000000000000000000000000000000000000...,Nueva,1,1-ORD HST 50 AÃO 364 DIA,0,0.0,0,0,66,2019-04-12,2021-08-25,0,1,6,1,ORDEN NACIONAL,Policia Nacional,NACIONAL CENTRALIZADA,1000003,13544804

In [6]:
lib = lib[lib['id_cli'].notnull()]
lib['id_cli'] = lib['id_cli'].astype('int')
lib['id_cliente'] = lib['id_cliente'].astype('str')
lib['standard_id'] = lib['standard_id'].astype('int')

In [7]:
lib['ds_estado_actual'] = lib['ds_estado_actual'].str.upper()
ids = lib.loc[~lib['ds_estado_actual'].isin(['CANCELADO', 'EN COBRO JURIDICO', 'CASTIGO MANUAL', 
                                            'CASTIGO SISTEMATIZADO', 'CANCELADO POR REESTRUCTURADA']),['id_cli', 'standard_id','id_cliente']].drop_duplicates()

ids_final = ids.rename(columns = {'id_cli':'id_numero_cliente'})
ids_final['fecha_camp'] = int(anio+mes)
ids_final.shape

(326737, 4)

In [8]:
ids_final.head(15)

     id_numero_cliente  standard_id          id_cliente  fecha_camp
0             13544804      1000003  102652295880533801      202110
20             6880226      1000003  102652295151150201      202110
42            41311613      1000003  102652314595088801      202110
44            36695801      1000003  102652308842687701      202110
48            23173372      1000003  103552297266851902      202110
55             9520719      1000003  102652312041465801      202110
60             7184314      1000003  103552306699911002      202110
62             8785282      1000003  103552295372280802      202110
67             3714784      1000003  102652294765177701      202110
86            27079010      1000003  102652297589965301      202110
94            14972564      1000003  102652296060855001      202110
100           80354687      1000003  102652304429247101      202110
113           11222544      1000003  102652295542372001      202110
118           27076024      1000003  102652297598623801      202110
164           30038179      1000003  103552314534549702      202110

In [9]:
# # Data Demog

# path = 's3://data-bpop-dev-sandbox/estandarizado/clientes/identificacion/clientes_identificacion_mdm_D20210218'
# data_demog = spark_read_parquet(path)
# data_demog = data_demog[data_demog['ref_num'].str.isdigit()]
# print(data_demog.shape)
# data_demog.head(5)

In [10]:
# # Join cedula, typeid
# data_demog = data_demog.rename(columns={'cont_id':'id_cliente',
#                                        'ref_num':'id_numero_cliente'})

# data_demog['id_tp_cd'] = data_demog['id_tp_cd'].astype('str')

# data_demog = data_demog.drop_duplicates(subset=['id_tp_cd', 'id_numero_cliente'], keep='first') ## Problemas de duplicados

In [11]:
# data_demog['id_cliente'] = data_demog['id_cliente'].fillna('-99').astype(np.int64)

In [12]:
# ids_final = pd.merge(ids_final,data_demog[['id_cliente','id_numero_cliente','id_tp_cd']], on='id_cliente', how='left')
# ids_final.count()

In [13]:
ids_final.head()

    id_numero_cliente  standard_id          id_cliente  fecha_camp
0            13544804      1000003  102652295880533801      202110
20            6880226      1000003  102652295151150201      202110
42           41311613      1000003  102652314595088801      202110
44           36695801      1000003  102652308842687701      202110
48           23173372      1000003  103552297266851902      202110

In [14]:
"s3://adl-refined-dev-popular/parquet/TC_adquisicion/base_ini"+anio+mes

's3://adl-refined-dev-popular/parquet/TC_adquisicion/base_ini202110'

In [15]:
## Guardando bases
ids_final.to_parquet("s3://adl-refined-dev-popular/parquet/TC_adquisicion/base_ini"+anio+mes,engine='pyarrow', index=False)

In [16]:
aaaaaaaaa

NameError: name 'aaaaaaaaa' is not defined

In [ ]:
"""
MODULE: processing_filtering
This script extracts activos information from the activos file
Steps:
1. Get activos file
2. Get the needed columns and rows from activos file including the needed historical period
3. Create additional columns
"""

def processing_filtering(input_paths_activos):
    """Pending docstring"""
    # 1. Get filter file
    ids_final = get_filtering_file(input_paths_activos)
    print('get_filtering_file')
    # 2. Get demog file
    data_demog = get_demog_file(path)
    print('get_demog_file')
    # 3. Join between 
    ids_final2 = pd.merge(ids_final,data_demog[['id_cliente','id_numero_cliente','id_tp_cd']], on='id_cliente', how='left')
    print('ids_final_df')
    print('filtering_df created successfully')

    return ids_final2


def get_filtering_file(input_path):
    """ Gets the input_path to the activos file, drops some not useful columns
     and outputs a DataFrame
    :param input_path to activos file location
    :return: DataFrame
    """
    
    mes = '01'  ### REVISAR!!!!
    anio = '2021'   ### REVISAR!!!!
    
    filtering_file_path = input_path
    filtering = spark_read_parquet(filtering_file_path)

    filtering.rename(columns=lambda x: x.lower(), inplace=True)
    
    # Filter and casting variables
    filtering = filtering[filtering['id_cliente'].notnull()]
    filtering['id_cliente'] = filtering['id_cliente'].astype('int')
    
    ids = filtering.loc[~filtering['ds_estado_actual'].isin(['Cancelada','Castigado']),'id_cliente'].unique()
    ids_final = pd.DataFrame({'id_cliente':ids})
    ids_final['fecha_camp'] = int(anio+mes)  ### REVISAR!!!!

    return ids_final


def get_demog_file(path):
    """ Gets the input_path to the activos file, drops some not useful columns
     and outputs a DataFrame
    :param input_path to activos file location
    :return: DataFrame
    """
    
    print(path)
    # read the new table
    data_demog = spark_read_parquet(path)
    data_demog = data_demog[data_demog['ref_num'].str.isdigit()]

    # Join cedula, typeid and casting variables
    data_demog = data_demog.rename(columns={'cont_id':'id_cliente',
                                       'ref_num':'id_numero_cliente'})
    data_demog['id_tp_cd'] = data_demog['id_tp_cd'].astype('str')
    
    # Drop duplicates and casting variables
    data_demog = data_demog.drop_duplicates(subset=['id_tp_cd', 'id_numero_cliente'], keep='first')
    data_demog['id_cliente'] = data_demog['id_cliente'].fillna('-99').astype(np.int64)

    return data_demog

In [ ]:
mes = '01'
anio = '2021'
input_paths_activos = 's3://data-bpop-dev-sandbox/estandarizado/productos/libranzas/productos_libranzas_dwh_M'+anio+mes
path = 's3://data-bpop-dev-sandbox/estandarizado/clientes/identificacion/clientes_identificacion_mdm_D20210218'

ids_final2 = processing_filtering(input_paths_activos)

print(ids_final2.shape)
ids_final2.head()