# Creaci√≥n Variables del Pasivo

In [1]:
# cuentas_out['prom_dias_desde_ult_trans'] = gp_cuentas['dias_desde_ultima_trans'].mean()
# cuentas_out['prom_antiguedad_cuenta'] = gp_cuentas['antiguedad'].mean()

In [2]:
import pandas as pd 
import numpy as np 

pd.set_option('max_columns',None)
#pd.set_option('max_rows',100)

from datetime import datetime, timedelta 
from dateutil import relativedelta

#pd.set_option('max_columns',False)
#pd.set_option('display.float_format', lambda x: '%.3f' % x)

In [3]:
# path_in="s3://adl-refined-dev-popular/propension/raw_piloto/producto/pasivo/2018/"
# #path_in = "s3://adl-refined-dev-popular/data_orig/productos/pasivo/productos_pasivo_aaatr_M2020"
# path_out = "s3://adl-refined-dev-popular/data_orig/productos/pasivo/productos_pasivo_aaatr_M2020"


# for i in range(1,4):
    
#     if i<=9: var_aux = '0'+str(i)
#     else: var_aux = str(i)
        
#     data = pd.read_csv(path_in+var_aux+".csv",sep=",",encoding='utf_8',
#                         dtype={'id_cliente':'str','ID_CLIENTE':'str','nro_cuenta':str,'NRO_CUENTA':str})
    
#     print('Periodo 2020',var_aux)
#     print(data.shape)
    
#     data.to_csv(path_out+var_aux+"2.csv",sep="|",encoding='utf_8', index= False)
    
#     del data

In [4]:
# def func_dates(tabla_final,date):
#     if date == '201907':
#         tabla_final['fecha_apertura'] = pd.to_datetime(tabla_final['fecha_apertura'], dayfirst= True)
#         tabla_final['fecha_ultima_transaccion'] = pd.to_datetime(tabla_final['fecha_ultima_transaccion'], dayfirst= True)
#     elif date in dates2:
#         tabla_final['fecha_apertura'] = pd.to_datetime(tabla_final['fecha_apertura'], format='%d/%m/%Y')
#         tabla_final['fecha_ultima_transaccion'] = pd.to_datetime(tabla_final['fecha_ultima_transaccion'], format='%d/%m/%Y')
#     else:
#         tabla_final['fecha_apertura'] = pd.to_datetime(tabla_final['fecha_apertura'], format='%Y%m%d',errors='coerce')
#         tabla_final['fecha_ultima_transaccion'] = pd.to_datetime(tabla_final['fecha_ultima_transaccion'], format='%Y%m%d',errors='coerce')
        
#     return tabla_final

## Creando pasivos Total

In [5]:
# path_in="s3://adl-refined-dev-popular/data_orig/productos/pasivo/"

# str_dates = ['201801','201802','201803','201804','201805','201806','201807','201808','201809','201810','201811','201812',
#             '201901','201902','201903','201904','201905','201906','201907','201908','201909','201910','201911','201912',
#             '202001','202002','202003','202003']

# # str_dates = ['202004']

# product_type_dict = {'1':'corriente', '2':'ahorro', '3':'cdt'}


# dates1 = ['201904','201908','201909','201910','201911','201912','202001','202002','202003','202004','202005','202006']
# dates2 = ['201801','201802','201803','201804','201805','201806','201807','201808','201809','201810','201811','201812',
#          '201901','201902','201903','201905','201906','201907']

# for ix, date in enumerate(str_dates):
    
#     print('Periodo:',date)
#     if ix == 0:
#         tabla_final = pd.read_csv(path_in+"productos_pasivo_aaatr_M"+date+".csv",sep="|",encoding='utf_8',
#                     dtype={'id_cliente':'str','ID_CLIENTE':'str','nro_cuenta':str,'NRO_CUENTA':str})
#         tabla_final.columns = tabla_final.columns.str.lower()
        
#         ## Cambiar tipo producto:
#         tabla_final['periodo'] = int(date)
#         tabla_final['tipo_producto'] = tabla_final['cod_producto'].apply(lambda x: str(x)[0]).map(product_type_dict)
#         tabla_final = func_dates(tabla_final,date)
        
#         print(tabla_final.shape)  
        
#     else:
        
#         tabla_temp = pd.read_csv(path_in+"productos_pasivo_aaatr_M"+date+".csv",sep="|",encoding='utf_8',
#                     dtype={'id_cliente':'str','ID_CLIENTE':'str','nro_cuenta':str,'NRO_CUENTA':str})
#         tabla_temp.columns = tabla_temp.columns.str.lower()
        
#         ## Cambiar tipo producto:
#         tabla_temp['periodo'] = int(date)
#         tabla_temp['tipo_producto'] = tabla_temp['cod_producto'].apply(lambda x: str(x)[0]).map(product_type_dict)
#         tabla_temp = func_dates(tabla_temp,date)
        
#         print(tabla_temp.shape)
        
#         tabla_final = pd.concat([tabla_final,tabla_temp], ignore_index=True)
        
        
#         del tabla_temp

In [6]:
# tabla_final2 = tabla_final.copy()

In [7]:
import s3fs
import pyarrow.parquet as pq

fs = s3fs.S3FileSystem()

def read_parquet(date):

    input_path = path_in+'productos_pasivo_aaatr_M'+date
    input = input_path
    dataset = pq.ParquetDataset(input, filesystem=fs)
    lib = dataset.read()
    lib = lib.to_pandas()

    del dataset
    
    return lib

In [8]:
path_in="s3://data-bpop-dev-sandbox/estandarizado/productos/pasivo/"

# str_dates = ['201801','201802','201803','201804','201805','201806','201807','201808','201809','201810','201811','201812',
#             '201901','201902','201903','201904','201905','201906','201907','201908','201909','201910','201911','201912',
#             '202001','202002','202003','202004','202005','202006','202007','202008','202009','202010','202011','202012']

str_dates = ['202102','202103','202104']


product_type_dict = {'1':'corriente', '2':'ahorro', '3':'cdt'}


for ix, date in enumerate(str_dates):
    
    tabla_temp = read_parquet(date)
    tabla_temp.columns = tabla_temp.columns.str.lower()

    ## Cambiar tipo producto:
    tabla_temp['periodo'] = int(date)
    tabla_temp['tipo_producto'] = tabla_temp['cod_producto'].apply(lambda x: str(x)[0]).map(product_type_dict)

    print(tabla_temp.shape)
    
    print('Periodo:',date)
    if ix == 0:
        tabla_final = tabla_temp
    else:
        tabla_final = pd.concat([tabla_final,tabla_temp], ignore_index=True)
         
    del tabla_temp

/home/jupyter/anaconda3/lib/python3.7/site-packages/pyarrow/pandas_compat.py:752: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  labels, = index.labels

(693024, 17)
Periodo: 202012
(686872, 17)
Periodo: 202101
(685895, 17)
Periodo: 202102

In [9]:
## Cast dates
tabla_final['fecha_apertura'] = pd.to_datetime(tabla_final['fecha_apertura'])
tabla_final['fecha_ultima_transaccion'] = pd.to_datetime(tabla_final['fecha_ultima_transaccion'])

In [10]:
# tabla_final2 = tabla_final2.drop_duplicates()
# tabla_final = tabla_final.drop_duplicates()

# tabla_final = pd.concat([tabla_final,tabla_final2], ignore_index=True)

In [11]:
tabla_final.columns

Index(['sk_cliente', 'id_cliente', 'tipo_id', 'cod_producto', 'nro_cuenta',
       'fecha_ultima_transaccion', 'fecha_apertura', 'estado', 'saldo',
       'promedio1', 'promedio2', 'promedio3', 'promedio4', 'promedio5',
       'promedio6', 'periodo', 'tipo_producto'],
      dtype='object')

In [12]:
tabla_final.reset_index(inplace=True)

In [13]:
tabla_final = tabla_final.drop(columns={'index'})

In [14]:
print(tabla_final.shape)
tabla_final

(2065791, 17)

,sk_cliente,id_cliente,tipo_id,cod_producto,nro_cuenta,fecha_ultima_transaccion,fecha_apertura,estado,saldo,promedio1,promedio2,promedio3,promedio4,promedio5,promedio6,periodo,tipo_producto
0,589512,193655260482175901,1,230,230470139130,2020-08-05,2009-09-21,Activa,4734.0,44,4734,4734.0,4734,13496.0,27817.0,202012,ahorro
1,383846,176655242662434501,1,230,230269037354,2020-11-11,2019-03-11,Activa,9297.0,43,9297,86939.0,775019,2529867.0,1727435.0,202012,ahorro
2,None,None,1,230,230040255697,2021-01-04,2020-05-04,Activa,266.0,52,215273,124869.0,91883,112030.0,119374.0,202012,ahorro
3,1879480,628654886748163501,1,230,230364696526,2020-07-28,2018-12-13,Activa,13002.0,15,13002,13002.0,13002,21763.0,33351.0,202012,ahorro
4,3531065,463556583560250501,1,230,230353075104,2020-12-28,2019-06-17,Activa,639.0,57,6613,46606.0,37181,23836.0,3480.0,202012,ahorro
5,None,None,1,230,230098057920,2020-12-24,2019-12-10,Activa,8370.0,73,19794,159311.0,21052,8783.0,9952.0,202012,ahorro
6,None,None,1,230,230098057144,2021-01-05,2019-12-10,Activa,153473.0,76,101264,96966.0,132870,167686.0,39083.0,202012,ahorro
7,3524680,117956583634699602,1,230,230362350845,2021-01-04,2019-05-29,Activa,783598.0,41,558523,152489.0,4128,11892.0,309150.0,202012,ahorro
8,3513263,135456584306096301,1,230,230098048994,2020-12-22,2019-06-11,Activa,4520.0,67,12229,70751.0,47195,2136.0,9673.0,202012,ahorro
9,None,None,1,230,230026181784,2021-01-02,2019-12-16,Activa,9727.0,17,66898,132743.0,66185,83451.0,40072.0,202012,ahorro
10,3243249,973852312739260801,1,230,230083005991,2021-01-04,2014-10-29,Activa,477524.0,63,622589,159686.0,268946,25413.0,194092.0,202012,ahorro
11,3553164,905156961066247301,1,230,230650419971,2020-12-02,2019-09-23,Activa,8059.0,18,84816,1513674.0,1407416,1176707.0,162075.0,202012,ahorro
12,None,None,1,230,230350400370,2020-12-29,2019-11-28,Activa,7061.0,49,16849,619656.0,288640,597613.0,15920.0,202012,ahorro
13,783302,257653272701308901,1,230,230440164044,2021-01-04,2018-02-16,Activa,2035091.0,89,1859172,2568147.0,1803586,728003.0,827574.0,202012,ahorro
14,None,None,1,230,230360202881,2020-12-29,2019-11-19,Activa,2863.0,53,2370,10595.0,1417,869.0,1931.0,202012,ahorro
15,None,None,1,230,230392154365,2021-01-02,2019-10-31,Activa,210936.0,19,102084,87000.0,86307,44293.0,26319.0,202012,ahorro
16,1567397,423555361977114301,1,230,230353071178,2020-11-19,2019-02-19,Activa,11686.0,12,11686,129729.0,971863,916416.0,901127.0,202012,ahorro
17,None,None,1,230,230098062375,2020-12-31,2020-03-12,Activa,36949.0,71,75949,90327.0,11134,44507.0,491041.0,202012,ahorro
18,3485099,806756468325404502,1,230,230470130154,2020-08-04,2008-07-22,Activa,2843.0,27,2843,2843.0,2843,2843.0,144697.0,202012,ahorro
19,2375376,784953425410433201,4,230,230050159417,2020-12-25,2018-03-14,Activa,6770.0,55,14902,16107.0,370119,929546.0,355386.0,202012,ahorro
20,None,None,1,230,230098059058,2020-12-29,2020-02-25,Activa,1791.0,56,453050,260610.0,148231,645895.0,77523.0,202012,ahorro
21,1214792,396252312872571202,1,230,230018252791,2020-12-28,2017-03-23,Activa,2495.0,82,23463,2495.0,2495,2495.0,84753.0,202012,ahorro
22,963454,277154888859633901,1,230,230160159992,2020-10-16,2018-11-23,Activa,5937.0,42,5937,5937.0,146311,934049.0,106378.0,202012,ahorro
23,None,None,1,230,230350400149,2020-12-28,2019-11-27,Activa,131.0,66,18775,6577.0,47020,25650.0,1862.0,202012,ahorro
24,2733626,881452316843711801,1,230,230061114187,2020-12-31,2016-09-05,Activa,522914.0,5,130062,47674.0,89470,49589.0,106120.0,202012,ahorro
25,3523553,999656584026725701,1,230,230026171124,2020-09-08,2019-05-31,Activa,497.0,8,497,497.0,497,1052.0,2877.0,202012,ahorro
26,3318956,502855485089118201,1,230,230039148564,2020-12-21,2019-04-09,Activa,2011409.0,9,2230672,764524.0,807895,681058.0,578751.0,202012,ahorro
27,3438560,489155723724753002,1,230,230098044365,2020-11-03,2019-02-28,Activa,2288.0,51,2288,15621.0,220346,328164.0,102351.0,202012,ahorro
28,3513743,267256584354099001,1,230,230035146919,2021-01-04,2019-05-30,Activa,2256.0,32,2256,2256.0,2256,2256.0,2256.0,202012,ahorro
29,3501795,934856583169661001,1,230,230116027053,2020-12-28,2019-06-19,Activa,3451.0,51,25950,256989.0,104831,23422.0,198628.0,202012,ahorro
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2065761,765402,306452294296630402,1,210,210018240028,2021-02-05,2000-08-31,Activa,3065.0,9,133585,154715.0,113305,99635.0,123334.0,202102,ahorro
2065762,389829,227552295443034101,1,230,230193763828,2021-02-24,2003-06-05,Activa,1118302.0,8,251242,214372.0,611131,468644.0,40195.0,202102,ahorro
2065763,2264005,714552295443059502,1,230,230410014187,2021-03-01,2002-09-25,Activa,12824859.0,87,12706968,12458499.0,13403882,12751776.0,14742769.0,202102,ahorro
2065764,213529,122252295443122302,1,230,230450118278,2020-10-13,2008-02-29,Activa,283.0,1,283,283.0,283,283.0,370060.0,202102,ahorro
2065765,3078569,903352295443010101,1,230,230059049940,2021-02-25,2021-02-18,Activa,152297084.0,9,55379702,0.0,0,0.0,0.0,202102,ahorro
2065766,857320,364252295443045601,1,230,230180853004,2021-02-25,2001-05-31,Activa,8393.0,4,269417,76683.0,398233,379063.0,153732.0,202102,ahorro
2065767,793156,297952295443013002,1,230,230470216474,2020-09-10,2020-07-23,Activa,5101.0,25,5101,5101.0,5101,5101.0,5101.0,202102,ahorro
2065768,575504,177152295443600902,1,230,230240758656,2021-03-01,1999-08-31,Activa,1131540.0,11,342136,244926.0,335131,454099.0,149653.0,202102,ahorro
2065769,1862234,561352294296614202,1,210,210025069568,2021-03-01,1997-05-09,Activa,6000.0,22,675827,788053.0,1743383,542689.0,993116.0,202102,ahorro
2065770,503509,158852309402324501,1,230,230366039642,2020-09-24,2004-06-09,Activa,6949.0,69,6949,6949.0,6949,6949.0,6949.0,202102,ahorro
2065771,1258618,409552295443241102,1,230,230720001056,2020-11-10,2002-06-06,Activa,1943.0,21,1943,1943.0,1943,10109915.0,40005876.0,202102,ahorro
2065772,2512868,746152309251171601,1,230,230015016561,2021-02-26,2004-02-09,Activa,1407.0,26,71711,4898.0,66809,3404.0,5133.0,202102,ahorro
2065773,682139,227552309687838601,1,210,210620060574,2021-01-29,2004-02-26,Activa,1108.0,44,1108,1589.0,295065,6844.0,49044.0,202102,ahorro
2065774,3126855,891352307088439601,1,230,230280202680,2020-12-18,2008-09-04,Activa,9860.0,28,9860,9860.0,485991,130336608.0,10077928.0,202102,ahorro
2065775,3165136,985952295443158102,1,230,230391010428,2021-02-25,2003-09-08,Activa,1796.0,35,86391,45016.0,143366,162196.0,41340.0,202102,ahorro
2065776,1176671,379352305476776402,1,210,210620061580,2021-02-09,2004-02-27,Activa,8239.0,12,221192,717753.0,3544211,671933.0,466220.0,202102,ahorro
2065777,1389787,517452295443204201,1,230,230520764697,2021-03-01,2002-05-07,Activa,2461910.0,54,652333,424247.0,823809,639234.0,325277.0,202102,ahorro
2065778,2770764,832152295443194901,1,230,230098004351,2021-03-01,2017-09-04,Activa,1198080.0,71,3980077,145.0,145,145.0,145.0,202102,ahorro
2065779,1939671,561352295443225602,1,210,210140303546,2021-02-26,1999-12-09,Activa,3486.0,32,122018,114126.0,133001,552408.0,185908.0,202102,ahorro
2065780,2932151,796952295443393701,1,210,210587117011,2021-02-25,2002-08-22,Activa,2402636.0,19,1591301,2286662.0,3991417,2577673.0,2311763.0,202102,ahorro
2065781,647812,197254266336235402,1,230,230364018531,2021-03-01,2002-09-02,Activa,1543466.0,78,226363,320484.0,849839,689525.0,83421.0,202102,ahorro
2065782,1738361,572852295443235802,1,230,230023762057,2021-02-26,2001-07-05,Activa,889906.0,75,1053174,1319008.0,2304082,3949342.0,4409374.0,202102,ahorro
2065783,370926,194152295443278502,1,230,230470026592,2021-02-26,2004-01-08,Activa,3534.0,24,40529,46694.0,385041,329657.0,14467.0,202102,ahorro
2065784,2405869,833752295443441602,1,210,210405071929,2021-03-01,2002-07-18,Activa,1097641.0,84,606650,1108084.0,491661,793086.0,461183.0,202102,ahorro
2065785,3135464,927552295443354802,1,210,210640312286,2021-02-25,2002-08-16,Activa,178255.0,36,147521,55223.0,583672,514386.0,5379.0,202102,ahorro
2065786,2618473,758952307367168402,1,230,230470064189,2021-02-25,2006-04-03,Activa,7748.0,11,79842,240227.0,1448281,786386.0,474419.0,202102,ahorro
2065787,2483365,725955242634580402,1,230,230470202490,2021-03-01,2019-03-06,Activa,9007738.0,21,7324854,3120290.0,2823995,1880848.0,2096519.0,202102,ahorro
2065788,2756764,862252308256137301,1,230,230251018529,2021-02-24,2005-03-15,Activa,1395469.0,18,299492,320279.0,356540,674589.0,310739.0,202102,ahorro
2065789,3115603,881452305336560101,1,300,30018002817195,1997-03-07,2021-02-19,Depositado,1500000.0,535714,29,0.0,0,0.0,0.0,202102,cdt
2065790,3115603,881452305336560101,1,300,30018002822823,1997-03-07,2015-10-06,Depositado,600000.0,600000,0,0.0,0,0.0,0.0,202102,cdt

In [15]:
tabla_final.count()

sk_cliente                  1967547
id_cliente                  1967547
tipo_id                     2065791
cod_producto                2065791
nro_cuenta                  2065791
fecha_ultima_transaccion    2032805
fecha_apertura              2065782
estado                      2065791
saldo                       2065791
promedio1                   2065791
promedio2                   2065791
promedio3                   2065791
promedio4                   2065791
promedio5                   2065791
promedio6                   2065791
periodo                     2065791
tipo_producto               2065791
dtype: int64

In [16]:
tabla_final.tail()

,sk_cliente,id_cliente,tipo_id,cod_producto,nro_cuenta,fecha_ultima_transaccion,fecha_apertura,estado,saldo,promedio1,promedio2,promedio3,promedio4,promedio5,promedio6,periodo,tipo_producto
2065786,2618473,758952307367168402,1,230,230470064189,2021-02-25,2006-04-03,Activa,7748.0,11,79842,240227.0,1448281,786386.0,474419.0,202102,ahorro
2065787,2483365,725955242634580402,1,230,230470202490,2021-03-01,2019-03-06,Activa,9007738.0,21,7324854,3120290.0,2823995,1880848.0,2096519.0,202102,ahorro
2065788,2756764,862252308256137301,1,230,230251018529,2021-02-24,2005-03-15,Activa,1395469.0,18,299492,320279.0,356540,674589.0,310739.0,202102,ahorro
2065789,3115603,881452305336560101,1,300,30018002817195,1997-03-07,2021-02-19,Depositado,1500000.0,535714,29,0.0,0,0.0,0.0,202102,cdt
2065790,3115603,881452305336560101,1,300,30018002822823,1997-03-07,2015-10-06,Depositado,600000.0,600000,0,0.0,0,0.0,0.0,202102,cdt

In [17]:
tabla_final.dtypes

sk_cliente                          object
id_cliente                          object
tipo_id                             object
cod_producto                        object
nro_cuenta                          object
fecha_ultima_transaccion    datetime64[ns]
fecha_apertura              datetime64[ns]
estado                              object
saldo                              float64
promedio1                            int64
promedio2                            int64
promedio3                          float64
promedio4                            int64
promedio5                          float64
promedio6                          float64
periodo                              int64
tipo_producto                       object
dtype: object

In [18]:
tabla_final.groupby('periodo').size()

periodo
202012    693024
202101    686872
202102    685895
dtype: int64

In [19]:
## eliminando comas:

# tabla_final['saldo'] = [float(str(x).replace(',','.')) for x in tabla_final['saldo']]
# tabla_final['promedio1'] = [float(str(x).replace(',','.')) for x in tabla_final['promedio1']]
# tabla_final['promedio2'] = [float(str(x).replace(',','.')) for x in tabla_final['promedio2']]
# tabla_final['promedio3'] = [float(str(x).replace(',','.')) for x in tabla_final['promedio3']]
# tabla_final['promedio4'] = [float(str(x).replace(',','.')) for x in tabla_final['promedio4']]
# tabla_final['promedio5'] = [float(str(x).replace(',','.')) for x in tabla_final['promedio5']]
# tabla_final['promedio6'] = [float(str(x).replace(',','.')) for x in tabla_final['promedio6']]

In [20]:
tabla_final.head()

,sk_cliente,id_cliente,tipo_id,cod_producto,nro_cuenta,fecha_ultima_transaccion,fecha_apertura,estado,saldo,promedio1,promedio2,promedio3,promedio4,promedio5,promedio6,periodo,tipo_producto
0,589512,193655260482175901,1,230,230470139130,2020-08-05,2009-09-21,Activa,4734.0,44,4734,4734.0,4734,13496.0,27817.0,202012,ahorro
1,383846,176655242662434501,1,230,230269037354,2020-11-11,2019-03-11,Activa,9297.0,43,9297,86939.0,775019,2529867.0,1727435.0,202012,ahorro
2,None,None,1,230,230040255697,2021-01-04,2020-05-04,Activa,266.0,52,215273,124869.0,91883,112030.0,119374.0,202012,ahorro
3,1879480,628654886748163501,1,230,230364696526,2020-07-28,2018-12-13,Activa,13002.0,15,13002,13002.0,13002,21763.0,33351.0,202012,ahorro
4,3531065,463556583560250501,1,230,230353075104,2020-12-28,2019-06-17,Activa,639.0,57,6613,46606.0,37181,23836.0,3480.0,202012,ahorro

In [21]:
tabla_final.tail()

,sk_cliente,id_cliente,tipo_id,cod_producto,nro_cuenta,fecha_ultima_transaccion,fecha_apertura,estado,saldo,promedio1,promedio2,promedio3,promedio4,promedio5,promedio6,periodo,tipo_producto
2065786,2618473,758952307367168402,1,230,230470064189,2021-02-25,2006-04-03,Activa,7748.0,11,79842,240227.0,1448281,786386.0,474419.0,202102,ahorro
2065787,2483365,725955242634580402,1,230,230470202490,2021-03-01,2019-03-06,Activa,9007738.0,21,7324854,3120290.0,2823995,1880848.0,2096519.0,202102,ahorro
2065788,2756764,862252308256137301,1,230,230251018529,2021-02-24,2005-03-15,Activa,1395469.0,18,299492,320279.0,356540,674589.0,310739.0,202102,ahorro
2065789,3115603,881452305336560101,1,300,30018002817195,1997-03-07,2021-02-19,Depositado,1500000.0,535714,29,0.0,0,0.0,0.0,202102,cdt
2065790,3115603,881452305336560101,1,300,30018002822823,1997-03-07,2015-10-06,Depositado,600000.0,600000,0,0.0,0,0.0,0.0,202102,cdt

In [22]:
## Cast variables

tabla_final = tabla_final[tabla_final['id_cliente'].notnull()]
tabla_final = tabla_final[tabla_final['nro_cuenta'].isna()==False]

tabla_final['id_cliente'] = tabla_final['id_cliente'].astype('int64')
tabla_final['nro_cuenta'] = tabla_final['nro_cuenta'].astype('int64')
tabla_final['cod_producto'] = tabla_final['cod_producto'].astype('int64')

# tabla_final['saldo'] = tabla_final['saldo'].astype('float64')
# tabla_final['promedio1'] = tabla_final['promedio1'].astype('float64')
# tabla_final['promedio2'] = tabla_final['promedio2'].astype('float64')
# tabla_final['promedio3'] = tabla_final['promedio3'].astype('float64')
# tabla_final['promedio4'] = tabla_final['promedio4'].astype('float64')
# tabla_final['promedio5'] = tabla_final['promedio5'].astype('float64')
# tabla_final['promedio6'] = tabla_final['promedio6'].astype('float64')
tabla_final['fecha_apertura'] = pd.to_datetime(tabla_final['fecha_apertura'], format='%Y-%m-%d')
tabla_final['fecha_ultima_transaccion'] = pd.to_datetime(tabla_final['fecha_ultima_transaccion'], format='%Y-%m-%d')

In [23]:
tabla_final[tabla_final['periodo'] == 202102].count()

sk_cliente                  652111
id_cliente                  652111
tipo_id                     652111
cod_producto                652111
nro_cuenta                  652111
fecha_ultima_transaccion    641695
fecha_apertura              652108
estado                      652111
saldo                       652111
promedio1                   652111
promedio2                   652111
promedio3                   652111
promedio4                   652111
promedio5                   652111
promedio6                   652111
periodo                     652111
tipo_producto               652111
dtype: int64

In [24]:
tabla_final.dtypes

sk_cliente                          object
id_cliente                           int64
tipo_id                             object
cod_producto                         int64
nro_cuenta                           int64
fecha_ultima_transaccion    datetime64[ns]
fecha_apertura              datetime64[ns]
estado                              object
saldo                              float64
promedio1                            int64
promedio2                            int64
promedio3                          float64
promedio4                            int64
promedio5                          float64
promedio6                          float64
periodo                              int64
tipo_producto                       object
dtype: object

In [25]:
tabla_final[tabla_final['periodo'] == 202102].head()

,sk_cliente,id_cliente,tipo_id,cod_producto,nro_cuenta,fecha_ultima_transaccion,fecha_apertura,estado,saldo,promedio1,promedio2,promedio3,promedio4,promedio5,promedio6,periodo,tipo_producto
1379896,589512,193655260482175901,1,230,230470139130,2021-02-28,2009-09-21,Activa,4041523.0,2703615,4734,4734.0,4734,4734.0,13496.0,202102,ahorro
1379897,383846,176655242662434501,1,230,230269037354,2021-02-22,2019-03-11,Activa,329298.0,6,89297,9297.0,9297,86939.0,775019.0,202102,ahorro
1379899,3531065,463556583560250501,1,230,230353075104,2021-02-27,2019-06-17,Activa,8855.0,65,34987,70401.0,6613,46606.0,37181.0,202102,ahorro
1379902,3524680,117956583634699602,1,230,230362350845,2021-02-28,2019-05-29,Activa,953260.0,97,1087687,861495.0,558523,152489.0,4128.0,202102,ahorro
1379903,3513263,135456584306096301,1,230,230098048994,2021-01-23,2019-06-11,Activa,2484.0,72,2484,101035.0,12229,70751.0,47195.0,202102,ahorro

In [26]:
tabla_final = tabla_final[tabla_final['id_cliente'] != -1]

In [27]:
tabla_final['fecha'] = pd.to_datetime(tabla_final['periodo'], format='%Y%m')

In [28]:
periodo = 202104

In [29]:
path_in="s3://adl-refined-dev-popular/parquet/TC_adquisicion/base_pasivos_tot_M"

tabla_final.to_parquet(path_in+str(periodo), engine='pyarrow',index=False)

# Cargando Data

In [30]:
import gc
gc.collect()

235

In [31]:
path_in = "s3://adl-refined-dev-popular/parquet/TC_adquisicion/base_pasivos_tot_M"
periodo = 202102

In [32]:
pasivo_201803_202003 = pd.read_parquet(path_in+str(periodo), engine='pyarrow')

/home/jupyter/anaconda3/lib/python3.7/site-packages/pyarrow/pandas_compat.py:708: FutureWarning: .labels was deprecated in version 0.24.0. Use .codes instead.
  labels = getattr(columns, 'labels', None) or [
/home/jupyter/anaconda3/lib/python3.7/site-packages/pyarrow/pandas_compat.py:735: FutureWarning: the 'labels' keyword is deprecated, use 'codes' instead
  return pd.MultiIndex(levels=new_levels, labels=labels, names=columns.names)

In [33]:
pasivo_201803_202003.head()

,sk_cliente,id_cliente,tipo_id,cod_producto,nro_cuenta,fecha_ultima_transaccion,fecha_apertura,estado,saldo,promedio1,promedio2,promedio3,promedio4,promedio5,promedio6,periodo,tipo_producto,fecha
0,589512,193655260482175901,1,230,230470139130,2020-08-05,2009-09-21,Activa,4734.0,44,4734,4734.0,4734,13496.0,27817.0,202012,ahorro,2020-12-01
1,383846,176655242662434501,1,230,230269037354,2020-11-11,2019-03-11,Activa,9297.0,43,9297,86939.0,775019,2529867.0,1727435.0,202012,ahorro,2020-12-01
2,1879480,628654886748163501,1,230,230364696526,2020-07-28,2018-12-13,Activa,13002.0,15,13002,13002.0,13002,21763.0,33351.0,202012,ahorro,2020-12-01
3,3531065,463556583560250501,1,230,230353075104,2020-12-28,2019-06-17,Activa,639.0,57,6613,46606.0,37181,23836.0,3480.0,202012,ahorro,2020-12-01
4,3524680,117956583634699602,1,230,230362350845,2021-01-04,2019-05-29,Activa,783598.0,41,558523,152489.0,4128,11892.0,309150.0,202012,ahorro,2020-12-01

In [34]:
## Validaci√≥n de duplicados a nivel 'id_cliente','nrooblig','fecha'

In [35]:
pasivo_201803_202003=pasivo_201803_202003.sort_values(['id_cliente','nro_cuenta','periodo'])

In [36]:
#Se eliminan duplicados
pasivo_201803_202003=pasivo_201803_202003.drop_duplicates(subset=['id_cliente','nro_cuenta','periodo'],keep='first')

In [37]:
pasivo_201803_202003.shape

(1963902, 18)

In [38]:
pasivo_201803_202003['fecha_pasivo']=pasivo_201803_202003['periodo'].astype(int)

In [39]:
##Creacion variables SMLV

In [40]:
pasivo_201803_202003['ano_po'] = pasivo_201803_202003['periodo'].astype('str').str[0:4].astype(int)

#Se asigna el salario minimo mensual vigente de 2018 y 2019
pasivo_201803_202003['SMLV'] = np.where(pasivo_201803_202003['ano_po'] == 2018, 781242,
                                        np.where(pasivo_201803_202003['ano_po'] == 2019, 828116,
                                                 np.where(pasivo_201803_202003['ano_po'] == 2020, 877803,
                                                          np.where(pasivo_201803_202003['ano_po'] == 2021, 908526,
                                                          np.nan))))

In [41]:
pasivo_201803_202003['dia_fecha_corte'] = pasivo_201803_202003['fecha']+timedelta(days=37) ##TODO: Confirmar d√≠as

In [42]:
pasivo_201803_202003

,sk_cliente,id_cliente,tipo_id,cod_producto,nro_cuenta,fecha_ultima_transaccion,fecha_apertura,estado,saldo,promedio1,promedio2,promedio3,promedio4,promedio5,promedio6,periodo,tipo_producto,fecha,fecha_pasivo,ano_po,SMLV,dia_fecha_corte
626623,440856,101052294083942902,3,250,250180964801,2010-02-19,2006-06-16,Activa,0.0,0,0,0.0,0,0.0,0.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
1281605,440856,101052294083942902,3,250,250180964801,2010-02-19,2006-06-16,Activa,0.0,0,0,0.0,0,0.0,0.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1933793,440856,101052294083942902,3,250,250180964801,2010-02-19,2006-06-16,Activa,0.0,0,0,0.0,0,0.0,0.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
578282,491822,101052314032556001,1,230,230034135194,2020-10-15,2020-09-21,Activa,3745.0,75,3745,3745.0,1543542,14998348.0,0.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
1233696,491822,101052314032556001,1,230,230034135194,2020-10-15,2020-09-21,Activa,3745.0,75,3745,3745.0,3745,1543542.0,14998348.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1885995,491822,101052314032556001,1,230,230034135194,2020-10-15,2020-09-21,Activa,3745.0,75,3745,3745.0,3745,3745.0,1543542.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
493051,285985,101052315812399301,1,230,230015162027,2020-12-18,2016-02-17,Activa,675466.0,79,507040,43504.0,305,47873.0,47178.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
1149032,285985,101052315812399301,1,230,230015162027,2021-01-18,2016-02-17,Activa,5489.0,9,276130,507040.0,43504,305.0,47873.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1801590,285985,101052315812399301,1,230,230015162027,2021-01-18,2016-02-17,Activa,5489.0,9,5489,276130.0,507040,43504.0,305.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
427711,441894,101055253543395201,1,230,230070100219,2020-12-24,2006-10-06,Activa,12223412.0,24,11213426,11095224.0,7964281,6404090.0,5764757.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
1084006,441894,101055253543395201,1,230,230070100219,2021-01-27,2006-10-06,Activa,13238679.0,7,12085069,11213426.0,11095224,7964281.0,6404090.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1736521,441894,101055253543395201,1,230,230070100219,2021-03-01,2006-10-06,Activa,15208914.0,71,13591362,12085069.0,11213426,11095224.0,7964281.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
100532,474963,101055260650910902,1,230,230090112699,2020-10-14,2009-11-20,Activa,0.0,15,0,0.0,197566,282131.0,3058.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
759078,474963,101055260650910902,1,230,230090112699,2020-10-14,2009-11-20,Activa,0.0,15,0,0.0,0,197566.0,282131.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1412140,474963,101055260650910902,1,230,230090112699,2020-10-14,2009-11-20,Activa,0.0,15,0,0.0,0,0.0,197566.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
66385,474177,101055260683554401,1,230,230362172215,2020-12-28,2008-11-04,Activa,11425809.0,92,1482216,9109.0,9109,9109.0,9109.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
725463,474177,101055260683554401,1,230,230362172215,2021-01-20,2008-11-04,Activa,5952000.0,91,7757952,1482216.0,9109,9109.0,9109.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1378903,474177,101055260683554401,1,230,230362172215,2021-02-17,2008-11-04,Activa,10372.0,36,3408336,7757952.0,1482216,9109.0,9109.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
64917,433524,101055260826556001,1,230,230540186855,2021-01-04,2014-03-20,Activa,27664464.0,9,5652990,2194254.0,2133512,3903033.0,3298655.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
724015,433524,101055260826556001,1,230,230540186855,2021-01-31,2014-03-20,Activa,5355574.0,67,16615471,5652990.0,2194254,2133512.0,3903033.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1377469,433524,101055260826556001,1,230,230540186855,2021-02-26,2014-03-20,Activa,1131862.0,8,2211212,16615471.0,5652990,2194254.0,2133512.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
152306,275609,101055266367157902,1,230,230484126594,2020-12-05,2011-01-12,Activa,929504.0,58,377324,549895.0,34093,71223.0,1816.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
809998,275609,101055266367157902,1,230,230484126594,2021-01-06,2011-01-12,Activa,945808.0,3,260679,377324.0,549895,34093.0,71223.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1462560,275609,101055266367157902,1,230,230484126594,2021-03-01,2011-01-12,Activa,962104.0,6,205315,260679.0,377324,549895.0,34093.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
248555,212701,101055266603150201,1,230,230279005342,2020-12-31,2015-08-04,Activa,9572.0,6,48526,319088.0,8105,3323.0,6555.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
905561,212701,101055266603150201,1,230,230279005342,2021-02-01,2015-08-04,Activa,692682.0,76,75679,48526.0,319088,8105.0,3323.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1557925,212701,101055266603150201,1,230,230279005342,2021-02-27,2015-08-04,Activa,694493.0,46,84572,75679.0,48526,319088.0,8105.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
347400,3337766,101055629594214801,1,230,230574161022,2021-01-04,2019-02-07,Activa,1118607.0,45,271513,2288456.0,732441,111073.0,2866.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
1003986,3337766,101055629594214801,1,230,230574161022,2021-01-04,2019-02-07,Activa,907464.0,7,199440,271513.0,2288456,732441.0,111073.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1656352,3337766,101055629594214801,1,230,230574161022,2021-02-28,2019-02-07,Activa,907157.0,2,236907,199440.0,271513,2288456.0,732441.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583180,3171318,999852304183175101,1,210,210141075630,2021-01-04,2003-07-02,Activa,21769478.0,64,18408899,13713574.0,14101547,14193162.0,15740128.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
1238553,3171318,999852304183175101,1,210,210141075630,2021-01-31,2003-07-02,Activa,11540822.0,41,16539673,18408899.0,13713574,14101547.0,14193162.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1890841,3171318,999852304183175101,1,210,210141075630,2021-02-28,2003-07-02,Activa,11740604.0,2,10170093,16539673.0,18408899,13713574.0,14101547.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
163613,2861990,999854931769255301,1,230,230014014245,2021-01-04,2005-08-29,Activa,659329.0,37,1355312,1783898.0,904593,1814908.0,964347.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
821234,2861990,999854931769255301,1,230,230014014245,2021-02-01,2005-08-29,Activa,2704992.0,54,895162,1355312.0,1783898,904593.0,1814908.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1473801,2861990,999854931769255301,1,230,230014014245,2021-03-01,2005-08-29,Activa,3558156.0,43,656324,895162.0,1355312,1783898.0,904593.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
74100,3237353,999855260756555202,1,230,230080223274,2020-11-13,2020-09-07,Activa,271.0,71,271,9849282.0,2328700,0.0,0.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
733027,3237353,999855260756555202,1,230,230080223274,2020-11-13,2020-09-07,Activa,271.0,71,271,271.0,9849282,2328700.0,0.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1386378,3237353,999855260756555202,1,230,230080223274,2020-11-13,2020-09-07,Activa,271.0,71,271,271.0,271,9849282.0,2328700.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
89962,3189096,999855260757141801,1,230,230280259391,2021-01-04,2011-07-15,Activa,2422517.0,3,392102,595087.0,745260,4970798.0,234268.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
748639,3189096,999855260757141801,1,230,230280259391,2021-01-27,2011-07-15,Activa,1239109.0,57,651668,392102.0,595087,745260.0,4970798.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1401816,3189096,999855260757141801,1,230,230280259391,2021-02-26,2011-07-15,Activa,1348216.0,37,368051,651668.0,392102,595087.0,745260.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
167185,3301749,999855266256209401,1,230,230560260788,2020-12-21,2017-07-19,Activa,628232.0,97,887297,1632109.0,4099764,5185380.0,5574857.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
824774,3301749,999855266256209401,1,230,230560260788,2020-12-21,2017-07-19,Activa,628286.0,29,628260,887297.0,1632109,4099764.0,5185380.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1477336,3301749,999855266256209401,1,230,230560260788,2020-12-21,2017-07-19,Activa,628334.0,45,628311,628260.0,887297,1632109.0,4099764.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
235599,3211548,999855266583332801,1,230,230345149827,2020-12-28,2015-08-25,Activa,10244598.0,1386710,378699,65515.0,5580,16591.0,4751.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
892658,3211548,999855266583332801,1,230,230345149827,2021-01-09,2015-08-25,Activa,453040.0,86,2494279,1386710.0,378699,65515.0,5580.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1545061,3211548,999855266583332801,1,230,230345149827,2021-02-04,2015-08-25,Activa,455129.0,58,99693,2494279.0,1386710,378699.0,65515.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
521382,3136054,999952311167062801,1,230,230484167119,2021-01-04,2018-01-05,Activa,1133518.0,6,216107,113244.0,46169,119661.0,26906.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
1177160,3136054,999952311167062801,1,230,230484167119,2021-02-02,2018-01-05,Activa,1154768.0,14,426320,216107.0,113244,46169.0,119661.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1829660,3136054,999952311167062801,1,230,230484167119,2021-02-11,2018-01-05,Activa,1456023.0,19,671530,426320.0,216107,113244.0,46169.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
191449,3221811,999955266125537901,1,210,210018127647,2021-01-04,2009-02-19,Activa,743162.0,3,73240,352579.0,32614,65625.0,279968.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
848841,3221811,999955266125537901,1,210,210018127647,2021-02-01,2009-02-19,Activa,772505.0,3,181485,73240.0,352579,32614.0,65625.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1501312,3221811,999955266125537901,1,210,210018127647,2021-03-01,2009-02-19,Activa,902951.0,3,161481,181485.0,73240,352579.0,32614.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
137016,2825727,999955266280699901,1,230,230425127685,2020-12-22,2012-01-16,Activa,22439734.0,12,20124991,10822619.0,8142630,5390724.0,2945877.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
794827,2825727,999955266280699901,1,230,230425127685,2021-01-29,2012-01-16,Activa,26120064.0,16,22797888,20124991.0,10822619,8142630.0,5390724.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1447467,2825727,999955266280699901,1,230,230425127685,2021-02-26,2012-01-16,Activa,28592558.0,76,26387027,22797888.0,20124991,10822619.0,8142630.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10
226364,2894827,999955266612957502,1,210,210460344260,2020-12-21,2004-12-21,Activa,450646.0,12,371673,266294.0,11030,2971.0,5037.0,202012,ahorro,2020-12-01,202012,2020,877803.0,2021-01-07
883457,2894827,999955266612957502,1,210,210460344260,2021-02-01,2004-12-21,Activa,483236.0,12,163482,371673.0,266294,11030.0,2971.0,202101,ahorro,2021-01-01,202101,2021,908526.0,2021-02-07
1535869,2894827,999955266612957502,1,210,210460344260,2021-03-01,2004-12-21,Activa,480713.0,12,54394,163482.0,371673,266294.0,11030.0,202102,ahorro,2021-02-01,202102,2021,908526.0,2021-03-10

### Creaci√≥n base a nivel id_cliente, fecha

In [43]:
pasivo_201803_202003_cli_fec=pd.DataFrame(pasivo_201803_202003.groupby(['id_cliente','periodo'])[['SMLV','fecha_pasivo']].max())

In [44]:
pasivo_201803_202003_cli_fec.shape

(1847224, 2)

In [45]:
pasivo_201803_202003_cli_fec.head()

                                SMLV  fecha_pasivo
id_cliente         periodo
101052294083942902 202012   877803.0        202012
                   202101   908526.0        202101
                   202102   908526.0        202102
101052314032556001 202012   877803.0        202012
                   202101   908526.0        202101

### Variables Pasivo

In [46]:
# N√∫mero de cuentas totales vigentes al punto de observaci√≥n
# N√∫mero de cuentas vigentes al punto de observaci√≥n tipo cta Y
# Dias desde la √∫ltima transacci√≥n
# Antig√ºedad del cliente con ctas del pasivo
# meses desde la √∫ltima apertura de cta
# Saldo total a fin de mes
# Saldo maximo a fin de mes
# Saldo m√≠nimo a fin de mes
# Saldo total x meses atr√°s
# Saldo promedio √∫ltimos x meses
# Saldo promedio √∫ltimos x meses por tipo cta Y
# tipo de cuenta Digital, nueva, etc.

In [47]:
pasivo_201803_202003.columns

Index(['sk_cliente', 'id_cliente', 'tipo_id', 'cod_producto', 'nro_cuenta',
       'fecha_ultima_transaccion', 'fecha_apertura', 'estado', 'saldo',
       'promedio1', 'promedio2', 'promedio3', 'promedio4', 'promedio5',
       'promedio6', 'periodo', 'tipo_producto', 'fecha', 'fecha_pasivo',
       'ano_po', 'SMLV', 'dia_fecha_corte'],
      dtype='object')

In [48]:
## Agrupaciones
gp_pasv = pasivo_201803_202003.groupby(['id_cliente','periodo'])
# gp_pasv_cc = pasivo_201803_202003[pasivo_201803_202003['tipo_producto']=='corriente'].groupby(['id_cliente','periodo'])
gp_pasv_ca = pasivo_201803_202003[pasivo_201803_202003['tipo_producto']=='ahorro'].groupby(['id_cliente','periodo'])
# gp_pasv_cdt = pasivo_201803_202003[pasivo_201803_202003['tipo_producto']=='cdt'].groupby(['id_cliente','periodo'])

In [49]:
## Antiguedad Total
pasivo_201803_202003_cli_fec['pasv_antig_total'] = (gp_pasv['dia_fecha_corte'].max() - 
                                                                gp_pasv['fecha_apertura'].min())/np.timedelta64(30, 'D')
## Numero meses ultima apertura
pasivo_201803_202003_cli_fec['pasv_num_meses_ult_apertura'] = (gp_pasv['dia_fecha_corte'].max() - 
                                                                gp_pasv['fecha_apertura'].max())/np.timedelta64(30, 'D')
## Dia √∫ltima transacci√≥n
pasivo_201803_202003_cli_fec['pasv_dias_desde_ultima_trans'] = (gp_pasv['dia_fecha_corte'].max() - 
                                                                gp_pasv['fecha_ultima_transaccion'].max())/np.timedelta64(1, 'D')
#

## Saldo Total por cartera fin de mes
pasivo_201803_202003_cli_fec['pasv_saldo_tot_fin_mes_smlv'] = (gp_pasv['saldo'].sum())/(gp_pasv['SMLV'].max())
# pasivo_201803_202003_cli_fec['pasv_saldo_cc_fin_mes_smlv'] = (gp_pasv_cc['saldo'].sum())/(gp_pasv_cc['SMLV'].max())
pasivo_201803_202003_cli_fec['pasv_saldo_ca_fin_mes_smlv'] = (gp_pasv_ca['saldo'].sum())/(gp_pasv_ca['SMLV'].max())
# pasivo_201803_202003_cli_fec['pasv_saldo_cdt_fin_mes_smlv'] = (gp_pasv_cdt['saldo'].sum())/(gp_pasv_cdt['SMLV'].max())

# Creando fecha
pasivo_201803_202003_cli_fec.reset_index(inplace=True)
pasivo_201803_202003_cli_fec['fecha'] = pd.to_datetime(pasivo_201803_202003_cli_fec['periodo'], format='%Y%m')

In [50]:
def gp_func(ids, date):
    fecha = pd.to_datetime(date, format='%Y%m')
    n_meses = [1]
    
    pasv_out = pd.DataFrame(index=ids) # this is different from the actual prod code
    
    for n in n_meses:
        col_name = 'pasv_saldo_total_'+str(n)+'mes_atras'
#         col_name_cc = 'pasv_saldo_cc_'+str(n)+'mes_atras'
        col_name_ca = 'pasv_saldo_ca_'+str(n)+'mes_atras'
#         col_name_cdt = 'pasv_saldo_cdt_'+str(n)+'mes_atras'
        date_past = fecha - timedelta(days=n*30)

        gp = pasivo_201803_202003_cli_fec[(pasivo_201803_202003_cli_fec['fecha']>date_past)&(pasivo_201803_202003_cli_fec['fecha']<=fecha)].groupby('id_cliente')
        
        pasv_out[col_name] = gp['pasv_saldo_tot_fin_mes_smlv'].sum()/n
#         pasv_out[col_name_cc] = gp['pasv_saldo_cc_fin_mes_smlv'].sum()/n
        pasv_out[col_name_ca] = gp['pasv_saldo_ca_fin_mes_smlv'].sum()/n
#         pasv_out[col_name_cdt] = gp['pasv_saldo_cdt_fin_mes_smlv'].sum()/n
        
    pasv_out['periodo'] = int(date)
    pasv_out.index.rename('id_cliente', inplace=True)
    pasv_out.reset_index(inplace=True)
    
    return pasv_out

In [51]:
str_dates = ['202012','202101','202102']

for ix, date in enumerate(str_dates):
    print(date)
    ids = pasivo_201803_202003_cli_fec.loc[pasivo_201803_202003_cli_fec['periodo']==int(date), 'id_cliente'].unique()
    
    if ix == 0:
        pasv_out = gp_func(ids, date)
    else:    
        pasv_temp = gp_func(ids, date)
        pasv_out = pd.concat([pasv_out, pasv_temp], ignore_index=True)

        
# ## Set_index
# pasivo_201803_202003_cli_fec.set_index(['id_cliente','periodo'], inplace=True)
# pasv_out.set_index(['id_cliente','periodo'], inplace=True)

202012
202101
202102

In [52]:
## Set_index
pasivo_201803_202003_cli_fec.set_index(['id_cliente','periodo'], inplace=True)
pasv_out.set_index(['id_cliente','periodo'], inplace=True)

In [53]:
pasivo_201803_202003_cli_fec_tot = pasivo_201803_202003_cli_fec.join(pasv_out, how='left')
print(pasv_out.shape)
print(pasivo_201803_202003_cli_fec.shape)
print(pasivo_201803_202003_cli_fec_tot.shape)

pasivo_201803_202003_cli_fec_tot.head()

(1847224, 2)
(1847224, 8)
(1847224, 10)

                                SMLV  fecha_pasivo  pasv_antig_total  \
id_cliente         periodo
101052294083942902 202012   877803.0        202012        177.300000
                   202101   908526.0        202101        178.333333
                   202102   908526.0        202102        179.366667
101052314032556001 202012   877803.0        202012          3.600000
                   202101   908526.0        202101          4.633333

                            pasv_num_meses_ult_apertura  \
id_cliente         periodo
101052294083942902 202012                    177.300000
                   202101                    178.333333
                   202102                    179.366667
101052314032556001 202012                      3.600000
                   202101                      4.633333

                            pasv_dias_desde_ultima_trans  \
id_cliente         periodo
101052294083942902 202012                         3975.0
                   202101                         4006.0
                   202102                         4037.0
101052314032556001 202012                           84.0
                   202101                          115.0

                            pasv_saldo_tot_fin_mes_smlv  \
id_cliente         periodo
101052294083942902 202012                      0.000000
                   202101                      0.000000
                   202102                      0.000000
101052314032556001 202012                      0.004266
                   202101                      0.004122

                            pasv_saldo_ca_fin_mes_smlv      fecha  \
id_cliente         periodo
101052294083942902 202012                     0.000000 2020-12-01
                   202101                     0.000000 2021-01-01
                   202102                     0.000000 2021-02-01
101052314032556001 202012                     0.004266 2020-12-01
                   202101                     0.004122 2021-01-01

                            pasv_saldo_total_1mes_atras  \
id_cliente         periodo
101052294083942902 202012                      0.000000
                   202101                      0.000000
                   202102                      0.000000
101052314032556001 202012                      0.004266
                   202101                      0.004122

                            pasv_saldo_ca_1mes_atras
id_cliente         periodo
101052294083942902 202012                   0.000000
                   202101                   0.000000
                   202102                   0.000000
101052314032556001 202012                   0.004266
                   202101                   0.004122

In [54]:
pasivo_201803_202003_cli_fec_tot.reset_index(inplace=True)

In [55]:
pasivo_201803_202003_cli_fec_tot = pasivo_201803_202003_cli_fec_tot.drop(['SMLV','periodo','fecha','pasv_saldo_ca_fin_mes_smlv','pasv_saldo_tot_fin_mes_smlv'], axis=1)

In [56]:
pasivo_201803_202003_cli_fec_tot.tail(50)

,id_cliente,fecha_pasivo,pasv_antig_total,pasv_num_meses_ult_apertura,pasv_dias_desde_ultima_trans,pasv_saldo_total_1mes_atras,pasv_saldo_ca_1mes_atras
1847174,999656652159656602,202101,133.400000,1.000000,6.0,82.256842,51.437691
1847175,999656652159656602,202102,134.433333,2.033333,13.0,89.457949,58.638798
1847176,999755260498918701,202012,64.233333,64.233333,3.0,3.587921,3.587921
1847177,999755260498918701,202101,65.266667,65.266667,12.0,2.857098,2.857098
1847178,999755260498918701,202102,66.300000,66.300000,9.0,2.502012,2.502012
1847179,999755260616443801,202012,52.500000,52.500000,12.0,1.148218,1.148218
1847180,999755260616443801,202101,53.533333,53.533333,18.0,1.127261,1.127261
1847181,999755260616443801,202102,54.566667,54.566667,15.0,0.047812,0.047812
1847182,999755266321666002,202012,132.800000,132.800000,8.0,0.005762,0.005762
1847183,999755266321666002,202101,133.833333,133.833333,11.0,0.242750,0.242750
1847184,999755266321666002,202102,134.866667,134.866667,9.0,1.334130,1.334130
1847185,999755266508527801,202012,121.766667,121.766667,3.0,0.027015,0.027015
1847186,999755266508527801,202101,122.800000,122.800000,6.0,0.031703,0.031703
1847187,999755266508527801,202102,123.833333,123.833333,9.0,0.035501,0.035501
1847188,999755266520683701,202012,3.933333,3.933333,73.0,0.005611,0.005611
1847189,999755266520683701,202101,4.966667,4.966667,104.0,0.005421,0.005421
1847190,999755266520683701,202102,6.000000,6.000000,135.0,0.005421,0.005421
1847191,999756149651647102,202012,134.600000,134.600000,3.0,4.819069,4.819069
1847192,999756149651647102,202101,135.633333,135.633333,6.0,4.822922,4.822922
1847193,999756149651647102,202102,136.666667,136.666667,12.0,4.257669,4.257669
1847194,999852304183175101,202012,213.300000,213.300000,3.0,24.799959,24.799959
1847195,999852304183175101,202101,214.333333,214.333333,7.0,12.702798,12.702798
1847196,999852304183175101,202102,215.366667,215.366667,10.0,12.922695,12.922695
1847197,999854931769255301,202012,187.000000,187.000000,3.0,0.751113,0.751113
1847198,999854931769255301,202101,188.033333,188.033333,6.0,2.977341,2.977341
1847199,999854931769255301,202102,189.066667,189.066667,9.0,3.916405,3.916405
1847200,999855260756555202,202012,4.066667,4.066667,55.0,0.000309,0.000309
1847201,999855260756555202,202101,5.100000,5.100000,86.0,0.000298,0.000298
1847202,999855260756555202,202102,6.133333,6.133333,117.0,0.000298,0.000298
1847203,999855260757141801,202012,115.466667,115.466667,3.0,2.759750,2.759750
1847204,999855260757141801,202101,116.500000,116.500000,11.0,1.363867,1.363867
1847205,999855260757141801,202102,117.533333,117.533333,12.0,1.483960,1.483960
1847206,999855266256209401,202012,42.266667,42.266667,17.0,0.715687,0.715687
1847207,999855266256209401,202101,43.300000,43.300000,48.0,0.691544,0.691544
1847208,999855266256209401,202102,44.333333,44.333333,79.0,0.691597,0.691597
1847209,999855266583332801,202012,65.400000,65.400000,10.0,11.670726,11.670726
1847210,999855266583332801,202101,66.433333,66.433333,29.0,0.498654,0.498654
1847211,999855266583332801,202102,67.466667,67.466667,34.0,0.500953,0.500953
1847212,999952311167062801,202012,36.600000,36.600000,3.0,1.291313,1.291313
1847213,999952311167062801,202101,37.633333,37.633333,5.0,1.271035,1.271035
1847214,999952311167062801,202102,38.666667,38.666667,27.0,1.602621,1.602621
1847215,999955266125537901,202012,144.666667,144.666667,3.0,0.846616,0.846616
1847216,999955266125537901,202101,145.700000,145.700000,6.0,0.850284,0.850284
1847217,999955266125537901,202102,146.733333,146.733333,9.0,0.993864,0.993864
1847218,999955266280699901,202012,109.300000,109.300000,16.0,25.563519,25.563519
1847219,999955266280699901,202101,110.333333,110.333333,9.0,28.749936,28.749936
1847220,999955266280699901,202102,111.366667,111.366667,12.0,31.471370,31.471370
1847221,999955266612957502,202012,195.366667,195.366667,17.0,0.513379,0.513379
1847222,999955266612957502,202101,196.400000,196.400000,6.0,0.531890,0.531890
1847223,999955266612957502,202102,197.433333,197.433333,9.0,0.529113,0.529113

In [57]:
pasivo_201803_202003_cli_fec_tot.to_parquet("s3://adl-refined-dev-popular/parquet/TC_adquisicion/base_pasivos_M"+str(periodo),engine='pyarrow', index=False)

In [58]:
prueba = pasivo_201803_202003_cli_fec_tot[pasivo_201803_202003_cli_fec_tot['fecha_pasivo'] == periodo]

In [59]:
prueba.head()

,id_cliente,fecha_pasivo,pasv_antig_total,pasv_num_meses_ult_apertura,pasv_dias_desde_ultima_trans,pasv_saldo_total_1mes_atras,pasv_saldo_ca_1mes_atras
2,101052294083942902,202102,179.366667,179.366667,4037.0,0.000000,0.000000
5,101052314032556001,202102,5.666667,5.666667,146.0,0.004122,0.004122
8,101052315812399301,202102,61.600000,61.600000,51.0,0.006042,0.006042
11,101055253543395201,202102,175.633333,175.633333,9.0,16.740208,16.740208
14,101055260650910902,202102,137.600000,137.600000,147.0,0.000000,0.000000

In [60]:
pasivo_201803_202003_cli_fec_tot['fecha_pasivo'].value_counts().sort_index()

202012    620143
202101    614666
202102    612415
Name: fecha_pasivo, dtype: int64